-- Breeze OS foundation schema (PR 1)
--
-- Generated by hand to match lib/db/schema.js exactly. Once the live DB
-- exists, `npm run db:generate` will produce its own migration file and
-- confirm there's no drift. Until then, this file is the source of truth
-- for the initial migration.

-- ── Enums ────────────────────────────────────────────────────────

CREATE TYPE "property_type" AS ENUM ('sfr', 'multi_family', 'commercial', 'mixed');
CREATE TYPE "utility_type" AS ENUM ('electric', 'gas', 'water', 'sewer', 'trash', 'internet', 'cable');
CREATE TYPE "account_holder" AS ENUM ('owner_llc', 'tenant');
CREATE TYPE "move_event_type" AS ENUM ('move_in', 'move_out');
CREATE TYPE "move_event_status" AS ENUM ('pending', 'in_progress', 'completed', 'escalated', 'cancelled');
CREATE TYPE "move_event_action" AS ENUM ('verify_off_llc', 'transfer_to_llc', 'verify_on_llc');
CREATE TYPE "move_event_item_status" AS ENUM ('pending', 'calling', 'on_hold', 'completed', 'failed', 'needs_human');
CREATE TYPE "call_purpose" AS ENUM ('move_event_utility', 'tenant_collection', 'generic');
CREATE TYPE "call_status" AS ENUM ('queued', 'ringing', 'in_progress', 'on_hold', 'completed', 'failed', 'no_answer');
CREATE TYPE "call_outcome" AS ENUM ('success', 'partial', 'on_hold_timeout', 'closed', 'needs_human', 'failed', 'voicemail');
CREATE TYPE "task_status" AS ENUM ('pending', 'claimed', 'completed', 'failed', 'cancelled');

-- ── Core ─────────────────────────────────────────────────────────

CREATE TABLE "organizations" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "name" text NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE "users" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "organization_id" uuid NOT NULL REFERENCES "organizations"("id") ON DELETE CASCADE,
  "email" text NOT NULL,
  "display_name" text,
  "role" text NOT NULL DEFAULT 'admin',
  "clerk_user_id" text,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX "users_org_idx" ON "users" ("organization_id");
CREATE INDEX "users_email_idx" ON "users" ("email");

-- ── Property directory ───────────────────────────────────────────

CREATE TABLE "owners" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "organization_id" uuid NOT NULL REFERENCES "organizations"("id") ON DELETE CASCADE,
  "legal_name" text NOT NULL,
  "dba" text,
  "ein_encrypted" text,
  "mailing_address_line1" text,
  "mailing_address_line2" text,
  "mailing_city" text,
  "mailing_state" text,
  "mailing_zip" text,
  "billing_email" text,
  "authorized_callers" jsonb,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX "owners_org_idx" ON "owners" ("organization_id");

CREATE TABLE "utility_providers" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "organization_id" uuid NOT NULL REFERENCES "organizations"("id") ON DELETE CASCADE,
  "name" text NOT NULL,
  "phone_number" text NOT NULL,
  "website" text,
  "business_hours" jsonb,
  "expected_hold_minutes" integer DEFAULT 5,
  "call_script_notes" text,
  "required_fields" jsonb,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX "utility_providers_org_idx" ON "utility_providers" ("organization_id");

CREATE TABLE "properties" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "organization_id" uuid NOT NULL REFERENCES "organizations"("id") ON DELETE CASCADE,
  "owner_id" uuid NOT NULL REFERENCES "owners"("id") ON DELETE RESTRICT,
  "rm_property_id" integer,
  "display_name" text NOT NULL,
  "property_type" "property_type" NOT NULL DEFAULT 'sfr',
  "service_address_line1" text NOT NULL,
  "service_address_line2" text,
  "service_city" text NOT NULL,
  "service_state" text NOT NULL,
  "service_zip" text NOT NULL,
  "billing_address_line1" text,
  "billing_address_line2" text,
  "billing_city" text,
  "billing_state" text,
  "billing_zip" text,
  "notes" text,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX "properties_org_idx" ON "properties" ("organization_id");
CREATE INDEX "properties_owner_idx" ON "properties" ("owner_id");
CREATE INDEX "properties_rm_idx" ON "properties" ("rm_property_id");

CREATE TABLE "property_utilities" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "property_id" uuid NOT NULL REFERENCES "properties"("id") ON DELETE CASCADE,
  "utility_type" "utility_type" NOT NULL,
  "provider_id" uuid REFERENCES "utility_providers"("id") ON DELETE SET NULL,
  "account_holder" "account_holder" NOT NULL,
  "billback_tenant" boolean NOT NULL DEFAULT false,
  "current_account_number" text,
  "notes" text,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX "property_utilities_property_idx" ON "property_utilities" ("property_id");
CREATE INDEX "property_utilities_provider_idx" ON "property_utilities" ("provider_id");

-- ── Move events ──────────────────────────────────────────────────

CREATE TABLE "move_events" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "organization_id" uuid NOT NULL REFERENCES "organizations"("id") ON DELETE CASCADE,
  "property_id" uuid NOT NULL REFERENCES "properties"("id") ON DELETE RESTRICT,
  "rm_tenant_id" integer,
  "tenant_display_name" text,
  "event_type" "move_event_type" NOT NULL,
  "effective_date" timestamptz NOT NULL,
  "status" "move_event_status" NOT NULL DEFAULT 'pending',
  "notes" text,
  "created_by_user_id" uuid REFERENCES "users"("id") ON DELETE SET NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX "move_events_org_idx" ON "move_events" ("organization_id");
CREATE INDEX "move_events_property_idx" ON "move_events" ("property_id");
CREATE INDEX "move_events_rm_tenant_idx" ON "move_events" ("rm_tenant_id");

CREATE TABLE "move_event_utilities" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "move_event_id" uuid NOT NULL REFERENCES "move_events"("id") ON DELETE CASCADE,
  "property_utility_id" uuid NOT NULL REFERENCES "property_utilities"("id") ON DELETE RESTRICT,
  "action" "move_event_action" NOT NULL,
  "status" "move_event_item_status" NOT NULL DEFAULT 'pending',
  "attempts" integer NOT NULL DEFAULT 0,
  "max_attempts" integer NOT NULL DEFAULT 5,
  "next_attempt_at" timestamptz,
  "from_account_number" text,
  "to_account_number" text,
  "confirmation_number" text,
  "notes" text,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX "move_event_utilities_move_event_idx" ON "move_event_utilities" ("move_event_id");
CREATE INDEX "move_event_utilities_status_idx" ON "move_event_utilities" ("status");

-- ── Infrastructure: calls, tasks, audit ──────────────────────────

CREATE TABLE "calls" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "organization_id" uuid NOT NULL REFERENCES "organizations"("id") ON DELETE CASCADE,
  "purpose" "call_purpose" NOT NULL,
  "related_table" text,
  "related_id" uuid,
  "vapi_call_id" text,
  "to_phone" text NOT NULL,
  "from_phone" text,
  "status" "call_status" NOT NULL DEFAULT 'queued',
  "outcome" "call_outcome",
  "started_at" timestamptz,
  "ended_at" timestamptz,
  "duration_seconds" integer,
  "cost_cents" integer,
  "transcript" text,
  "recording_url" text,
  "structured_output" jsonb,
  "error_code" text,
  "created_at" timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX "calls_org_idx" ON "calls" ("organization_id");
CREATE INDEX "calls_vapi_idx" ON "calls" ("vapi_call_id");
CREATE INDEX "calls_related_idx" ON "calls" ("related_table", "related_id");

CREATE TABLE "tasks" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "organization_id" uuid NOT NULL REFERENCES "organizations"("id") ON DELETE CASCADE,
  "kind" text NOT NULL,
  "payload" jsonb NOT NULL,
  "scheduled_for" timestamptz NOT NULL,
  "status" "task_status" NOT NULL DEFAULT 'pending',
  "attempts" integer NOT NULL DEFAULT 0,
  "last_error" text,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX "tasks_due_idx" ON "tasks" ("status", "scheduled_for");

CREATE TABLE "audit_events" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "organization_id" uuid NOT NULL REFERENCES "organizations"("id") ON DELETE CASCADE,
  "actor_type" text NOT NULL,
  "actor_id" text,
  "subject_table" text NOT NULL,
  "subject_id" uuid NOT NULL,
  "event_type" text NOT NULL,
  "before_state" jsonb,
  "after_state" jsonb,
  "created_at" timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX "audit_events_org_idx" ON "audit_events" ("organization_id");
CREATE INDEX "audit_events_subject_idx" ON "audit_events" ("subject_table", "subject_id");
